"""Planner workflow component for ResearchOps.

Deconstructs natural-language business questions into entities, scoping assumptions,
comparison dimensions, and discrete research jobs.
Specification: PRD.md Section 6.2 & TECH_SPEC.md Section 5.1.
"""

import logging
import os
from typing import List, Optional
import re
from pydantic import BaseModel, Field, model_validator

from app.integrations.openrouter import OpenRouterClient, OpenRouterError, get_openrouter_client
from app.models.enums import JobStatus
from app.models.job import ResearchJob

logger = logging.getLogger("researchops.planner")


class RawPlannerJob(BaseModel):
    """Raw sub-task description returned by the LLM."""

    description: str = Field(default="", description="Actionable web research instruction for the researcher")
    entity: Optional[str] = Field(default=None, description="Target company or entity being investigated")
    attribute: Optional[str] = Field(default=None, description="Specific dimension or metric to uncover")

    @model_validator(mode="before")
    @classmethod
    def normalize_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if not data.get("description") and data.get("task"):
                data["description"] = data["task"]
            elif not data.get("description") and data.get("instruction"):
                data["description"] = data["instruction"]
            if not data.get("attribute") and data.get("dimension"):
                data["attribute"] = data["dimension"]
            elif not data.get("attribute") and data.get("metric"):
                data["attribute"] = data["metric"]
        return data


class RawPlannerOutput(BaseModel):
    """Structured LLM output for research decomposition."""

    assumptions: List[str] = Field(
        default_factory=list,
        description="Explicit assumptions made to resolve ambiguity (e.g. market, timeframe, scope)",
    )
    entities: List[str] = Field(
        default_factory=list,
        description="List of target companies, products, or entities to research",
    )
    comparison_dimensions: List[str] = Field(
        default_factory=list,
        description="Key comparison criteria (e.g. Founded year, Pricing, Revenue, Market share)",
    )
    jobs: List[RawPlannerJob] = Field(
        default_factory=list,
        description="Independent, non-redundant research sub-tasks",
    )

    @model_validator(mode="before")
    @classmethod
    def unwrap_and_normalize(cls, data: Any) -> Any:
        if isinstance(data, dict):
            # Unwrap nested research_plan if present
            if "research_plan" in data and isinstance(data["research_plan"], dict):
                inner = data["research_plan"]
                for k, v in inner.items():
                    if k not in data or not data[k]:
                        data[k] = v
            # Normalize entities
            if not data.get("entities") and data.get("key_entities"):
                data["entities"] = data["key_entities"]
            elif not data.get("entities") and data.get("target_entities"):
                data["entities"] = data["target_entities"]
            # Normalize dimensions
            if not data.get("comparison_dimensions") and data.get("dimensions"):
                data["comparison_dimensions"] = data["dimensions"]
            # Normalize jobs
            if not data.get("jobs") and data.get("research_jobs"):
                data["jobs"] = data["research_jobs"]
            elif not data.get("jobs") and data.get("sub_tasks"):
                data["jobs"] = data["sub_tasks"]
        return data


class ResearchPlan(BaseModel):
    """Complete structured research plan generated by the Planner."""

    question: str = Field(description="Original research question")
    assumptions: List[str] = Field(description="Scoping assumptions")
    entities: List[str] = Field(description="Entities to investigate")
    comparison_dimensions: List[str] = Field(description="Comparison criteria")
    research_jobs: List[ResearchJob] = Field(description="Executable ResearchJob domain models")


PLANNER_SYSTEM_PROMPT = """You are the Lead Strategic Research Planner for "ResearchOps", an autonomous business intelligence system.
Your mission is to analyze a natural-language business question and break it down into an actionable, structured research plan.

CRITICAL INSTRUCTIONS FOR ENTITIES:
1. "entities" MUST strictly be actual commercial companies, vendors, competitors, or specific products (e.g. ["Bounce", "Yulu", "Vogo", "Zypp Electric"]).
2. NEVER include research topics, analytical themes, or report sections in "entities" (e.g. NEVER include "Risk Analysis", "Industry Report", "Market Data", "Customer Research", "Operational Benchmark", "Regulatory Compliance").
3. Limit "entities" to the top 3 to 5 real market players.
4. Consolidate vehicle models or variants under the parent brand (e.g. use "Yulu", NOT "Yulu Miracle" or "Yulu Wynn" as separate entities; use "Blusmart", NOT "Blusmart (potential expansion)").

CRITICAL INSTRUCTIONS FOR COMPARISON DIMENSIONS:
1. "comparison_dimensions" must be 3-4 concrete, measurable attributes compared across all entities (e.g. ["Pricing Models", "Vehicle Fleet & Specs", "Bengaluru Availability", "Target Customers"]).

CRITICAL INSTRUCTIONS FOR RESEARCH JOBS:
1. Each job must represent a discrete, targeted web research instruction.
2. In the "description", provide clear domain context and location (e.g. "Research Bounce electric scooter rental subscription pricing in Bengaluru").
3. Ensure every entity and dimension is covered symmetrically so no entity is left without data for any dimension.

Output format MUST strictly match this JSON structure:
{
  "assumptions": ["Assumption 1", "Assumption 2"],
  "entities": ["Entity A", "Entity B"],
  "comparison_dimensions": ["Pricing", "Speed", "Market Share"],
  "jobs": [
    {"entity": "Entity A", "attribute": "Pricing", "description": "Research Entity A pricing tiers and plans"},
    {"entity": "Entity B", "attribute": "Pricing", "description": "Research Entity B pricing tiers and plans"}
  ]
}
"""


class Planner:
    """Planner node that transforms business questions into structured ResearchPlans."""

    def __init__(self, openrouter_client: Optional[OpenRouterClient] = None):
        self.client = openrouter_client or get_openrouter_client()

    async def plan(self, question: str, research_run_id: str) -> ResearchPlan:
        """Generate a structured research plan for a given question.

        Args:
            question: Natural language business question.
            research_run_id: Research run identifier.

        Returns:
            ResearchPlan containing assumptions, entities, dimensions, and ResearchJob records.
        """
        clean_question = question.strip()
        if len(clean_question) < 5:
            raise ValueError("Research question must be at least 5 characters long.")

        logger.info("Planner generating research plan for run %s: '%s'", research_run_id, clean_question)

        # Attempt structured planning via OpenRouter LLM
        if self.client.is_configured:
            try:
                raw_output = await self._plan_with_llm(clean_question)
                return self._build_research_plan(clean_question, research_run_id, raw_output)
            except OpenRouterError as exc:
                logger.warning("LLM planning encountered error (%s); falling back to heuristic planner", exc)
            except Exception as exc:
                logger.error("Unexpected error during LLM planning: %s", exc, exc_info=True)

        # Fallback heuristic planner for offline tests or unconfigured environments
        logger.info("Using deterministic heuristic planner for run %s", research_run_id)
        raw_output = self._heuristic_plan(clean_question)
        return self._build_research_plan(clean_question, research_run_id, raw_output)

    async def _plan_with_llm(self, question: str) -> RawPlannerOutput:
        """Call OpenRouter with structured prompt."""
        messages = [
            {"role": "system", "content": PLANNER_SYSTEM_PROMPT},
            {"role": "user", "content": f"Deconstruct this business research question into a structured research plan:\n\n\"{question}\""},
        ]
        return await self.client.chat_structured(
            messages=messages,
            response_model=RawPlannerOutput,
            model=self.client.research_model,
            temperature=0.1,
        )

    def _build_research_plan(
        self,
        question: str,
        research_run_id: str,
        raw: RawPlannerOutput,
    ) -> ResearchPlan:
        """Convert raw LLM output into fully validated ResearchPlan with ResearchJob domain models."""
        # 1. Clean and filter entities
        DISALLOWED_ENTITY_TERMS = {
            "risk analysis", "industry report", "market data", "customer research",
            "operational benchmark", "regulatory compliance", "market overview",
            "general overview", "competitor comparison", "challenges", "opportunities",
            "market size", "regulations", "adoption indicators", "use cases",
            "charging infrastructure", "fleet management", "opportunities and risks",
            "benchmarks", "analysis", "report", "insights"
        }

        cleaned_entities: List[str] = []
        seen_entity_bases = set()
        for ent in raw.entities:
            if not ent or not isinstance(ent, str):
                continue
            e = ent.strip()
            e_base = re.sub(r'\(.*?\)', '', e).strip()
            if not e_base or len(e_base) < 2:
                continue
            if e_base.lower() in DISALLOWED_ENTITY_TERMS:
                continue
            if any(term in e_base.lower() for term in ("risk analysis", "industry report", "market data", "customer research", "operational benchmark", "regulatory compliance")):
                continue

            first_word = e_base.split()[0].lower()
            if first_word in seen_entity_bases:
                continue

            cleaned_entities.append(e_base)
            seen_entity_bases.add(first_word)
            if len(cleaned_entities) >= 5:
                break

        if not cleaned_entities:
            cleaned_entities = [e for e in raw.entities if e and isinstance(e, str)][:5] or ["Market Overview"]

        # 2. Clean comparison dimensions
        cleaned_dimensions: List[str] = []
        seen_dim_lower = set()
        for dim in raw.comparison_dimensions:
            if not dim or not isinstance(dim, str):
                continue
            d = dim.strip()
            d_lower = d.lower()
            if not d or len(d) < 2 or d_lower in seen_dim_lower:
                continue
            seen_dim_lower.add(d_lower)
            cleaned_dimensions.append(d)
            if len(cleaned_dimensions) >= 5:
                break

        if not cleaned_dimensions:
            cleaned_dimensions = ["Overview", "Key Features", "Pricing"]

        # 3. Build entity mapping for job association
        entity_name_map = {}
        for orig in raw.entities:
            c = re.sub(r'\(.*?\)', '', orig).strip()
            f_word = c.split()[0].lower() if c else ""
            for ce in cleaned_entities:
                if ce.lower() == c.lower() or ce.split()[0].lower() == f_word:
                    entity_name_map[orig] = ce
                    break

        jobs: List[ResearchJob] = []
        existing_pairs = set()

        for idx, r_job in enumerate(raw.jobs, start=1):
            mapped_entity = entity_name_map.get(r_job.entity, r_job.entity)
            if mapped_entity and mapped_entity.lower() in DISALLOWED_ENTITY_TERMS:
                continue
            job_id = f"job-{research_run_id[:8]}-{idx:02d}"
            job_ent = mapped_entity if mapped_entity in cleaned_entities else (cleaned_entities[0] if cleaned_entities else mapped_entity)
            job_attr = r_job.attribute or (cleaned_dimensions[0] if cleaned_dimensions else "Overview")
            pair = (job_ent.lower() if job_ent else "", job_attr.lower() if job_attr else "")
            existing_pairs.add(pair)
            jobs.append(
                ResearchJob(
                    id=job_id,
                    research_run_id=research_run_id,
                    description=r_job.description,
                    entity=job_ent,
                    attribute=job_attr,
                    status=JobStatus.PENDING,
                    attempts=0,
                )
            )

        # 4. Guarantee symmetric coverage: if an entity has 0 jobs, or pairs are missing, fill them
        researched_entities = {(j.entity or "").strip().lower() for j in jobs if j.entity}
        for ent in cleaned_entities:
            if ent.lower() not in researched_entities:
                for dim in cleaned_dimensions:
                    pair = (ent.lower(), dim.lower())
                    if pair not in existing_pairs:
                        job_id = f"job-{research_run_id[:8]}-{len(jobs) + 1:02d}"
                        jobs.append(
                            ResearchJob(
                                id=job_id,
                                research_run_id=research_run_id,
                                description=f"Investigate {ent} {dim} details and market specifications",
                                entity=ent,
                                attribute=dim,
                                status=JobStatus.PENDING,
                                attempts=0,
                            )
                        )
                        existing_pairs.add(pair)

        # Guard: ensure at least one general job exists if none provided
        if not jobs:
            jobs.append(
                ResearchJob(
                    id=f"job-{research_run_id[:8]}-01",
                    research_run_id=research_run_id,
                    description=f"Identify and research primary market entities for: {question}",
                    status=JobStatus.PENDING,
                )
            )

        return ResearchPlan(
            question=question,
            assumptions=raw.assumptions or ["Rely on latest publicly available disclosures"],
            entities=cleaned_entities,
            comparison_dimensions=cleaned_dimensions,
            research_jobs=jobs,
        )

    def _heuristic_plan(self, question: str) -> RawPlannerOutput:
        """Deterministic heuristic decomposition when external LLM is offline or in mock test."""
        lower_q = question.lower()
        assumptions = [
            "Scope restricted to publicly verifiable business intelligence",
            "Latest current market data prioritized",
        ]

        # 1. Multi-entity comparison extraction: e.g. "Compare Blinkit, Zepto, and Swiggy Instamart on delivery fees..."
        comp_match = re.search(r"^(?:compare\s+)(.+?)(?:\s+(?:on|across|for|in|based on)\s+(.+))?$", question.strip(), re.IGNORECASE)
        if comp_match:
            ent_part = comp_match.group(1).strip()
            dim_part = comp_match.group(2).strip() if comp_match.group(2) else ""

            # Extract comma/and-separated entities
            raw_ents = [re.sub(r"^(?:and|vs\.?|versus)\s+", "", e.strip(), flags=re.IGNORECASE).strip()
                        for e in re.split(r",|\band\b|\bvs\.?\b|\bversus\b", ent_part) if e.strip()]
            extracted_ents = [e for e in raw_ents if len(e) >= 2][:4]

            # Extract dimensions
            if dim_part:
                raw_dims = [re.sub(r"^(?:and\s+)", "", d.strip(), flags=re.IGNORECASE).strip().title()
                            for d in re.split(r",|\band\b", dim_part) if d.strip()]
                extracted_dims = [d for d in raw_dims if len(d) >= 2][:4]
            else:
                extracted_dims = ["Pricing", "Key Features", "Market Presence"]

            if len(extracted_ents) >= 2:
                entities = extracted_ents
                dimensions = extracted_dims or ["Pricing", "Market Presence"]
                jobs = []
                for ent in entities:
                    for dim in dimensions:
                        jobs.append(
                            RawPlannerJob(
                                description=f"Research {ent} {dim} pricing metrics and live data",
                                entity=ent,
                                attribute=dim,
                            )
                        )
                return RawPlannerOutput(
                    assumptions=assumptions,
                    entities=entities,
                    comparison_dimensions=dimensions,
                    jobs=jobs,
                )

        if "crm" in lower_q:
            entities = ["Zoho", "Freshworks", "Salesforce"]
            dimensions = ["Founded Year", "Headquarters", "Pricing Model", "Market Presence"]
            jobs = [
                RawPlannerJob(description="Identify major CRM providers and market share in India", entity="Market", attribute="Overview"),
                RawPlannerJob(description="Research Zoho CRM founding year, headquarters, and market segment", entity="Zoho", attribute="Founded & HQ"),
                RawPlannerJob(description="Research Zoho CRM pricing tiers and plans", entity="Zoho", attribute="Pricing"),
                RawPlannerJob(description="Research Freshworks CRM founding year, headquarters, and origin", entity="Freshworks", attribute="Founded & HQ"),
                RawPlannerJob(description="Research Freshworks CRM pricing tiers and plans", entity="Freshworks", attribute="Pricing"),
                RawPlannerJob(description="Research Salesforce CRM market presence and entry-level pricing in India", entity="Salesforce", attribute="Pricing & Presence"),
            ]
            for extra in ["stealthsaas", "leadsquared", "stealthco"]:
                if extra in lower_q:
                    canon = "StealthSaaS" if extra == "stealthsaas" else "LeadSquared" if extra == "leadsquared" else "StealthCo"
                    if canon not in entities:
                        entities.append(canon)
                    jobs.append(RawPlannerJob(description=f"Research {canon} pricing and plans", entity=canon, attribute="Pricing"))
        else:
            known = [
                "Zoho", "Freshworks", "Salesforce", "LeadSquared", "StealthSaaS", "StealthCo",
                "Bounce", "Yulu", "Vogo", "Linear", "Jira", "Stripe", "Adyen", "Datadog", "New Relic",
                "Blinkit", "Zepto", "Swiggy Instamart", "Swiggy", "Zomato", "Uber", "Ola"
            ]
            found = [k for k in known if k.lower() in lower_q]
            if found:
                entities = found
                dimensions = ["Pricing & Fees", "Operations & Availability", "Market Presence"]
                jobs = []
                for ent in entities:
                    for dim in dimensions:
                        jobs.append(RawPlannerJob(description=f"Research {ent} {dim} details official data", entity=ent, attribute=dim))
            else:
                # Dynamic comparison extraction: "Compare X vs Y on..."
                vs_match = re.search(r"(?:compare\s+)?([A-Za-z0-9\s\-]+?)\s+(?:vs\.?|versus|and)\s+([A-Za-z0-9\s\-]+?)(?:\s+(?:on|across|for|in)\s+|$)", question, re.IGNORECASE)
                if vs_match:
                    ent1 = vs_match.group(1).strip().title()
                    ent2 = vs_match.group(2).strip().title()
                    ent1 = re.sub(r"^(?:compare|the)\s+", "", ent1, flags=re.IGNORECASE).strip()
                    entities = [ent1, ent2]
                    
                    on_match = re.search(r"(?:on|across|for|in)\s+(.+)$", question, re.IGNORECASE)
                    if on_match:
                        dim_str = on_match.group(1).strip()
                        dims = [re.sub(r"^(?:and\s+)", "", d.strip()).strip().title() for d in re.split(r",|\band\b", dim_str) if d.strip()]
                        dimensions = dims[:4] if dims else ["Pricing", "Performance", "Market Presence"]
                    else:
                        dimensions = ["Pricing", "Core Features", "Market Presence"]

                    jobs = []
                    for ent in entities:
                        for dim in dimensions:
                            jobs.append(
                                RawPlannerJob(
                                    description=f"Research {ent} {dim} official data and benchmark metrics",
                                    entity=ent,
                                    attribute=dim,
                                )
                            )
                else:
                    # Clean extraction from question title
                    words = [w.strip() for w in question.split() if w.strip()]
                    topic_title = " ".join(words[:4]).title()
                    entities = [f"{topic_title} Service A", f"{topic_title} Service B"]
                    dimensions = ["Pricing & Plans", "Key Offerings", "Market Coverage"]
                    jobs = [
                        RawPlannerJob(description=f"Research market pricing and fees for {question}", entity=entities[0], attribute="Pricing & Plans"),
                        RawPlannerJob(description=f"Research operational details and coverage for {question}", entity=entities[1], attribute="Market Coverage"),
                    ]

        return RawPlannerOutput(
            assumptions=assumptions,
            entities=entities,
            comparison_dimensions=dimensions,
            jobs=jobs,
        )


def get_planner() -> Planner:
    """Dependency provider for Planner."""
    return Planner()
